services:
  doom-addon-s:
    build: .
    container_name: doom-addon-s
    restart: unless-stopped
    environment:
      HOST: 0.0.0.0
      PORT: 7000
      PROVIDER_TIMEOUT_MS: 70000
      STREAM_FIRST_BATCH_WAIT_MS: 8000
      STREAM_FAST_PROVIDER_WAIT_MS: 12000
      STREAM_QUALITY_SHARED_WAIT_MS: 60000
      STREAM_DIRECT_PLAYBACK_MODE: true
    ports:
      - "7002:7000"

  doom-addon-s-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: doom-addon-s-tunnel
    restart: unless-stopped
    depends_on:
      - doom-addon-s
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TOKEN}
